name: Generate PUML Diagram

on:
  pull_request:
    paths:
      - 'docs/c4/**.puml'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create Diagram PNG
        uses: Timmy/plantuml-action@v1
        with:
          args: './docs/c4/architecture.puml'

      - name: Check for Diagram Changes
        run: |
          git add ./docs/c4/architecture.png
          if ! git diff --cached --exit-code; then
            echo "Diagrams do not match. You can re-generate the diagram by running the command plantuml docs/c4/architecture.puml."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
